
// Objective-C API for talking to the following Go packages
//
//	github.com/rnSample
//
// File is generated by gomobile bind. Do not edit.
#ifndef __RnSample_FRAMEWORK_H__
#define __RnSample_FRAMEWORK_H__

#include "RnSample.objc.h"
#include "Universe.objc.h"

#endif
