// Objective-C API for talking to github.com/rnSample Go package.
//   gobind -lang=objc github.com/rnSample
//
// File is generated by gobind. Do not edit.

#ifndef __RnSample_H__
#define __RnSample_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT int32_t RnSampleAsyncSum(int32_t x, int32_t y, long sleepMs);

FOUNDATION_EXPORT int32_t RnSampleSyncSum(int32_t x, int32_t y);

#endif
